app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/*Route::get('/', array('as' => 'home', function() {
    die("teste");
    return View::make('site::index');
}));*/

Route::get('admin/logout',
    array('as' => 'admin.logout', 'uses' => 'App\Controllers\Admin\AuthController@getLogout'));

Route::get('admin/login',
    array('as' => 'admin.login', 'uses' => 'App\Controllers\Admin\AuthController@getLogin'));

Route::post('admin/login',
    array('as' => 'admin.login.post',  'uses' => 'App\Controllers\Admin\AuthController@postLogin'));

Route::group(array('prefix' => 'admin', 'before' => 'auth.admin'), function()
{
    Route::any('/',                'App\Controllers\ContactsController@index');
    Route::resource('contacts',       'App\Controllers\ContactsController');
});

app/views/admin/_layouts/default.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>L4 Site</title>
 
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <link href="{{ URL::asset('assets/css/main.css') }}" rel="stylesheet">
 
    <script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<div>
    <div>
        <div>
            <div>
                <a href="{{ URL::route('admin.contacts.index') }}">Sevengo Lading Page Admin</a>
 
                @if (Sentry::check())
                    <ul>
                        <li><a href="{{ URL::route('admin.contacts.index') }}"><i></i> Contacts</a></li>
                        <li><a href="{{ URL::route('admin.logout') }}"><i></i> Logout</a></li>
                    </ul>
                @endif
            </div>
        </div>
    </div>
 
    <hr>
 
    @yield('main')
</div>
</body>
</html>